version: "3.3"
services:
  postgres:
    container_name: postgres_container
    image: postgres:14.2
    restart: always
    environment:
      POSTGRES_DB: "postgresql"
      POSTGRES_USER: "postgresql_user"
      POSTGRES_PASSWORD: "user_password"
      PGDATA: "/var/lib/postgresql/data/pgdata"
    volumes:
      - ../2. Init Database:/docker-entrypoint-initdb.d
      - .:/var/lib/postgresql/data
    ports:
      - "54320:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgresql_user -d postgresql" ]
      timeout: 45s
      interval: 2s
      retries: 10
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 4G
    networks:
      - postgres_net

  pgadmin:
    container_name: pgadmin_container
    image: dpage/pgadmin4:5.7
    environment:
      PGADMIN_DEFAULT_EMAIL: "panov@codeblog.pro"
      PGADMIN_DEFAULT_PASSWORD: "pgadminpwd"
      PGADMIN_CONFIG_SERVER_MODE: "False"
    volumes:
      - ./pgadmin:/var/lib/pgadmin
    ports:
      - "5051:80"
    restart: always
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 1G
    networks:
      - postgres_net

networks:
  postgres_net:
    driver: bridge